version: '3'
services:
  app:
    build:
      context: ./
      args:
        WWWGROUP: '${WWWGROUP}'
    volumes:
      - ./database/database.sqlite:/var/www/database/database.sqlite
    environment:
      WWWUSER: '${WWWUSER}'
    container_name: cleantracker
    networks:
      - cleantracker
networks:
  cleantracker:
    driver: bridge
